include:
  - path: ../.docker/infra/docker-compose.yml
services:
  devcontainer-openclaw:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openclaw-devcontainer
    hostname: openclaw
    pull_policy: if_not_present
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_OPTIONS: "--max-old-space-size=4096"
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      TAILSCALE_AUTHKEY: ${TAILSCALE_AUTHKEY}
    ports:
      - "18789:18789"
    volumes:
      - .openclaw:/root/.openclaw:cached
      - ../.vscode:/workspace/.vscode
      - .openclaw:/root/.openclaw:rw
    #command: /usr/local/bin/tailscaled.sh
    #entrypoint: /usr/local/bin/entrypoint.sh
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    networks:
      - ollama-network
      - openclaw-network

volumes:
  vscode:
  ollama-data:
    name: ollama-data
    external: true
  vscode-data:
    name: vscode-data
    external: true

networks:
  openclaw-network:
    name: openclaw-network
    external: true
  ollama-network:
    name: ollama-network
    external: true
